name: notebook-smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  nbval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install notebook tooling
        run: |
          python -m pip install --upgrade pip
          pip install nbformat nbconvert nbval pytest
      - name: Run mock-mode notebook smoke tests
        run: |
          pytest --nbval-lax                 0-prologue-notebooks/00_hello_agent.ipynb                 1-basics-gauntlet-notebooks/01_streaming_basics.ipynb                 1-basics-gauntlet-notebooks/05_middleware_redaction_retry.ipynb
